---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vinay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: uber
  template:
   metadata:
     labels:
      app: uber

   spec:
     containers:
       - name: cont1
         image: nginx
         ports:
           - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: chaitanya
spec:
  type: LoadBalancer
  selector:
    app: uber
  ports:
    - port: 80
      targetPort: 80
